cats_rental/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
  resources :users
end

cats_rental/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats_rental/app/models/cat.rb
require 'action_view'
include ActionView::Helpers::DateHelper
class Cat < ApplicationRecord

  CAT_COLORS = %w(red white grey pink orange black).freeze

  validates :color, inclusion: CAT_COLORS
  validates :sex, inclusion: %w(M F)

  def age
    time_ago_in_words(birth_date)
  end

end

cats_rental/app/models/user.rb
class User < ApplicationRecord
  attr_reader :password

  validates :username, presence: true
  validates :password_digest, presence: { message: 'password can\'t be blank'}
  validates :password, length: { minimum: 6, allow_nil: true}

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

cats_rental/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

cats_rental/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      flash[:msg] = "Cat info is successfully saved!"
      redirect_to cats_url
    else
      @cat.errors.full_messages
      render 'new'
    end
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update_attributes(cat_params)
      flash[:msg] = "Cat info is successfully updated!"
    else
      @cat.errors.full_messages
      render 'edit'
    end
  end

  private


  def cat_params
    params.require(:cat).permit(:age, :birth_date, :color, :description, :name, :sex)
  end
end

cats_rental/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      render json: @user
    else
      render json: @user.errors.full_messages
    end
  end

  def destroy

  end

  private

  def user_params
    params.require(:user).permit(:username, :password_digest)
  end
end

cats_rental/app/helpers/application_helper.rb
module ApplicationHelper
end

cats_rental/app/views/cats/edit.html.erb
<h1>Edit your cat</h1>

<!-- name, birth_date,color,sex,description -->

<form action="<%= cat_url(@cat) %>" method="post">
  <input type="hidden" name="_method" value="patch">

  <label for="cat_name">Name</label>
  <input type="text" name="cat[name]" id="cat_name" value="<%= @cat.name %>">
  <br>

  <label for="cat_birth">Birth_day</label>
  <input type="date" name="cat[birth_date]" id="cat_birth" value=" <%= @cat.birth_date %> ">
  <br>

  <label for="cat_color">Color</label>
  <select name="cat[color]" id="cat_color">
    <option selected disabled >--Select a Color</option>
    <% Cat::CAT_COLORS.each do |color| %>
      <option <%= @cat.color == color ? "selected" : "" %>
        value=" <%= color %> ">
        <%= color.upcase %>
      </option>
    <% end %>
  </select>


</form>

cats_rental/app/views/cats/index.html.erb
<h1>Cat's list</h1>
<% flash.each do |ele,msg| %>
<%= msg %>
<% end %>
  <ul>


    <% @cats.each do |cat| %>
    <li><%= link_to cat.name, cat_url(cat) %></li>
    <% end %>
  </ul>

cats_rental/app/views/cats/new.html.erb
<h1>Add a new Cat</h1>

<form action="<%=cats_url%>" method="post">
  <label for="cat_name">Name</label>
  <input type="text" name="cat[name]" id="cat_name" value="">
  <br>

  <label for="cat_birth">Birth</label>
  <input type="date" name="cat[birth_date]" id="cat_birth"value="">
  <br>

  <label for="color">Color</label>
  <select id="color" name="cat[color]">
    <option selected disabled value="">--Select a Color--</option>
    <% Cat::CAT_COLORS.each do |color| %>
    <option value="<%= color %>"><%= color.upcase %></option>
    <% end %>
  </select>
  <br>

  <label for="cat_sex">Male</label>
  <input type="radio" name="cat[sex]" value="M" id="cat_sex">

  <label for="cat_sex">Female</label>
  <input type="radio" name="cat[sex]" value="F" id="cat_sex">
  <br>

  <label>Description
  <textarea name="cat[description]"></textarea>
  </label>
  <br>

  <input type="submit" value="Create">

</form>

cats_rental/app/views/cats/show.html.erb
<h1> <%= @cat.name %>'s profle</h1>
  <table>
    <tr>
      <th>name</th>
      <th>attribute</th>
    </tr>
    <% [:age, :birth_date, :name, :description].each do |attr| %>
    <tr>
      <td><%= attr %></td>
      <td><%= @cat.send(attr) %></td>
    </tr>
    <% end %>
  </table>

cats_rental/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatsRental</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

cats_rental/app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : new_user_url) %>
<% method = (user.persisted? ? "patch" : "post") %>
<% message = (user.persisted? ? "Update" : "Create") %>

<form action="<%= action %>" method="post">
  <input type="hidden"
         name="_method"
         value="<%= method %>">

  <input type="hidden"
         name="authenticity_token"
         value="form_authenticity_token">

  <label for="user_name">User Name</label>
  <input type="text" name="user[username]" id="user_name">
  <br>

  <label for="user_password">Password</label>
  <input type="password" name="user[password]" id="user_password">
  <br>

  <input type="submit" value="<%= message %>">


</form>

cats_rental/app/views/users/new.html.erb
<h1>Create a new User</h1>

<%= render 'form', user: @user  %>